[ДЗ-4] js-basic
Khanabeev/purple-dz pull request #8
Opened 2024-02-25 18:54 UTC by Khanabeev

2024-02-26 13:06 UTC, Levitinn requested changes
нужно переделать. я могу добавить две одинаковые таски с одним и тем же ИД. так быть не должно. ИД должен поставлять ты, в своей логике и следить за тем, чтобы при удалении одной таски, и добавлении новой, ид всегда были уникальными. это влечет за собой исправления и в 15 задаче

2024-02-26 19:18 UTC, Levitinn requested changes

2024-02-26 19:18 UTC, Levitinn commented on 15-task-object/script.js
не годится.
- твой код работает только при условии, что есть таски на этапе инициализации тудулиста, у которых прописаны ИД. если ид не будет, то все поломается.
- удали все лишние консоль логи перед МР
- удали все лишние комментарии перед МР

2024-02-26 20:42 UTC, Khanabeev commented on 15-task-object/script.js
удалил лишние логи и комментарии. Не согласен с первым пунктом, в коде если tasks массив пустой, то id = 1. [18 строка](https://github.com/Khanabeev/purple-dz/blob/2959a74c26882d54fd009722b4cd013dc0d1bc93/15-task-object/script.js#L18).

2024-02-27 15:58 UTC, Levitinn approved these changes

2024-02-27 15:58 UTC, Levitinn commented on 15-task-object/script.js
согласен, все корректно.

2024-02-27 15:58 UTC, Levitinn commented on 15-task-object/script.js
> +      ? Math.max(...this.tasks.map((el) => el.id)) + 1
map и так возвращает новый массив, спред оператор здесь не нужен

2024-02-27 18:16 UTC, Khanabeev commented on 15-task-object/script.js
> +      ? Math.max(...this.tasks.map((el) => el.id)) + 1
исправил, спасибо.

2024-02-27 18:17 UTC, merged